imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

operator:

  # Default values for tailscale-operator.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # hostname:
  logging: info
  authProxy: "false"

  revisionHistoryLimit: 10

  image:
    repository: tailscale/k8s-operator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  extraEnvs: []

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

secret:
  # Specifies whether an oauth secret should be created
  create: false
  # The name of the oauth secret to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # clientId:
  # clientSecret:

proxy:

  image:
    repository: tailscale/tailscale
    pullPolicy: IfNotPresent
    tag: "unstable"

  tags:
    - tag:k8s

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    # TODO unpin `proxies` once customizable proxy templates are supported
    name: "proxies"

rbac:
  create: true