{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "tailscale-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
    {{- with .Values.operator.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "tailscale-operator.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["*"]
{{- end }}
