{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tailscale-operator.operator.serviceAccountName" . }}
  labels:
    {{- include "tailscale-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
