{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "tailscale-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
    {{- with .Values.operator.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "tailscale-operator.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["events", "services", "services/status"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingresses/status"]
    verbs: ["*"]
{{- end }}
