name: go generate

on:
  push:
    branches:
      - main
      - "release-branch/*"
  pull_request:
    branches:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check 'go generate' is clean
        # The shell script invocation below is a temporary hack for
        # https://github.com/tailscale/tailscale/issues/4194. When
        # that issue is fixed, replace its invocation with:
        # go generate --tags=hermetic ./...
        run: |
          set -e
          ./.github/workflows/go-generate-without-stringer.sh
          echo
          echo
          git diff --name-only --exit-code || (echo "The files above need updating. Please run 'go generate'."; exit 1)
