name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Basic build
      run: go build ./cmd/...

    - name: macOS build
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build ./cmd/...

    - name: Windows build
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build ./cmd/...

    - name: Test build
      run: go test ./...

