name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 全部历史记录

    - name: Sync with Upstream
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        upstream_repository: tailscale/tailscale
        upstream_branch: main
        target_branch: main
        git_username: 'GitHub Action'
        git_email: 'pylyzeng@gmail.com'
        exclude_files: 'Dockerfile|docker-build.yml|sync-with-upstream.yml'
