# This is the post-merge CI that runs on on code pushed to our main branches.
# It's identical to the CI that runs in PR, with the addition that it notifies
# us in Slack on failure.
name: CI

on:
  push:
    branches:
      - "main"
      - "release-branch/*"

jobs:
  test:
    uses: tailscale/tailscale/.github/workflows/test.yml@${{ github.sha }}

  notify_slack:
    if: failure()
    needs: ["test"]
    runs-on: ubuntu-22.04
    steps:
    - name: notify  
      uses: ruby/action-slack@v3.0.0
      with:
        payload: |
          {
            "attachments": [{
              "title": "Failure: ${{ github.workflow }}",
              "title_link": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks",         
              "text": "${{ github.repository }}@${{ github.ref_name }}: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
              "fields": [{ "value": ${{ toJson(github.event.head_commit.message) }}, "short": false }],
              "footer": "${{ github.event.head_commit.committer.name }} at ${{ github.event.head_commit.timestamp }}",
              "color": "danger"
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
